apiVersion: apps/v1
kind: Deployment
metadata:
  name: vweb-v1
  labels:
    kiamol: ch09    
    app: vweb
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vweb
      version: v1
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vweb
        version: v1
    spec:
      containers:
        - name: web
          image: kiamol/ch09-vweb:v1
          ports:
            - name: http
              containerPort: 80

