apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-api
spec:
  selector:
    matchLabels:
      app: lab-numbers-api
      version: v1
  template:
    metadata:
      labels:
        app: lab-numbers-api
        version: v1
    spec:
      initContainers:
        # The app requires more than the common Linux default of 128
        - name: configure-sysctl
          image: alpine
          command:
            - sysctl
            - '-w'
            - fs.inotify.max_user_instances=8192
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: api
          image: kiamol/ch03-numbers-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-web
spec:
  selector:
    matchLabels:
      app: lab-numbers-web
      version: v1
  template:
    metadata:
      labels:
        app: lab-numbers-web
        version: v1
    spec:
      initContainers:
        # The app requires more than the common Linux default of 128
        - name: configure-sysctl
          image: alpine
          command:
            - sysctl
            - '-w'
            - fs.inotify.max_user_instances=8192
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: web
          image: kiamol/ch03-numbers-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-numbers-web-v2
spec:
  selector:
    matchLabels:
      app: lab-numbers-web
      version: v2
  template:
    metadata:
      labels:
        app: lab-numbers-web
        version: v2
    spec:
      initContainers:
        # The app requires more than the common Linux default of 128
        - name: configure-sysctl
          image: alpine
          command:
            - sysctl
            - '-w'
            - fs.inotify.max_user_instances=8192
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: web
          image: kiamol/ch03-numbers-web:v2