FROM mcr.microsoft.com/dotnet/core/sdk:3.1.301-nanoserver-1809 AS builder

WORKDIR /src
COPY src/Numbers.Api/Numbers.Api.csproj .
RUN dotnet restore

COPY src/Numbers.Api/ .
RUN dotnet publish -c Release -o /out Numbers.Api.csproj

# app image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.5-nanoserver-1809

ENV FailAfterCallCount=0

ENTRYPOINT ["dotnet", "/app/Numbers.Api.dll"]

WORKDIR /app
COPY --from=builder /out/ .