apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-api
spec:
  selector:
    matchLabels:
      app: numbers-api
  template:
    metadata:
      labels:
        app: numbers-api
    spec:
      initContainers:
        # The app requires more than the common Linux default of 128
        - name: configure-sysctl
          image: alpine
          command:
            - sysctl
            - '-w'
            - fs.inotify.max_user_instances=8192
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: api
          image: kiamol/ch03-numbers-api
