apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi
  labels:
    kiamol: ch15
spec:
  rules:
  - host: pi.kiamol.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pi-web
            port:
              number: 80