{
 "title": "Random Number API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{job=\"numbers-api\"}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"numbers-api\"}"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_io_kubernetes_pod_name=~\"numbers-api.*\", container_label_io_kubernetes_container_name=\"api\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container_label_io_kubernetes_pod_name=~\"numbers-api.*\", container_label_io_kubernetes_container_name=\"api\"}) / sum (kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pod",
   "type": "table",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"numbers-api.*\",job=\"kube-state-metrics\"} "
    }
   ]
  },
  {
   "title": "Labels",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "kube_pod_labels{pod=~\"numbers-api.*\"}"
    }
   ]
  }
 ]
}