{
 "title": "TODO List",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Todo Web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, method, instance) (http_requests_in_progress)"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "90th Percentile Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(code, job, method) (rate(http_request_duration_seconds_bucket{code=\"200\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tasks Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum without(job) (rate(todo_tasks_created_total[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"todo-web\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"todo-web\"}[5m]))"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{job=\"todo-proxy\"}[5m]))"
    }
   ]
  },
  {
   "title": "Connections (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{job=\"todo-proxy\"}[5m]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(nginx_connections_handled{job=\"todo-proxy\"}[5m]))",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"todo-proxy\"}",
     "legendFormat": "{{instance}}/active"
    },
    {
     "expr": "nginx_connections_reading{job=\"todo-proxy\"}",
     "legendFormat": "{{instance}}/reading"
    },
    {
     "expr": "nginx_connections_waiting{job=\"todo-proxy\"}",
     "legendFormat": "{{instance}}/waiting"
    },
    {
     "expr": "nginx_connections_writing{job=\"todo-proxy\"}",
     "legendFormat": "{{instance}}/writing"
    }
   ]
  }
 ]
}